// Sample data for the application
// This would be replaced by actual API calls to your backend

export const categories = [
  {
    id: "1",
    name: "Office Furniture",
    slug: "office-furniture",
    subcategories: [
      {
        id: "101",
        name: "Chairs",
        slug: "chairs",
        image: "/images/categories/chair.jpg",
      },
      {
        id: "102",
        name: "Sofas",
        slug: "sofas",
        image: "/images/categories/couch.jpg",
      },
      {
        id: "103",
        name: "Side Table",
        slug: "side-table",
        image: "/images/categories/side_table.jpg",
      },
      {
        id: "104",
        name: "Coffee Table",
        slug: "coffee-table",
        image: "/images/categories/coffee_table.jpg",
      },
      {
        id: "105",
        name: "Sofas",
        slug: "sofas",
        image: "/images/categories/couch.jpg",
      },
    ],
  },
  {
    id: "2",
    name: "Home Furniture",
    slug: "home-furniture",
    subcategories: [
      {
        id: "201",
        name: "Living Room",
        slug: "living-room",
        image: "/images/categories/living_room.jpg",
      },
      {
        id: "202",
        name: "Bedroom",
        slug: "bedroom",
        image: "/images/categories/bedroom.jpg",
      },
      {
        id: "203",
        name: "Dining Room",
        slug: "dining-room",
        image: "/images/categories/dinning_room.jpg",
      },
      {
        id: "204",
        name: "Kitchen",
        slug: "kitchen",
        image: "/images/categories/kitchen_room.jpg",
      },
      {
        id: "205",
        name: "Bathroom",
        slug: "bathroom",
        image: "/images/categories/bathroom.jpg",
      },
    ],
  },
];

export const products = [
  {
    id: "1",
    name: "Wooden Double Sofa",
    price: "৳12,000.00",
    oldPrice: "৳15,000.00",
    image: "/images/categories/couch.jpg",
    category: "home-furniture",
    subcategory: "sofas",
    featured: true,
    bestselling: true,
    latest: false,
    rating: 4.8,
    description:
      "Premium wooden double sofa with comfortable cushions. Perfect for your living room or office reception area.",
  },
  {
    id: "2",
    name: "Luxurious Turkish Style Sofa",
    price: "৳25,000.00",
    oldPrice: "৳30,000.00",
    image: "/images/products/turkise_sofa.jpg",
    category: "home-furniture",
    subcategory: "sofas",
    featured: true,
    bestselling: false,
    latest: true,
    rating: 4.9,
    description:
      "Elegant Turkish style sofa with premium upholstery and intricate detailing. Adds a touch of luxury to any space.",
  },
  {
    id: "3",
    name: "Modern L-Shaped Sofa Set",
    price: "৳50,000.00",
    oldPrice: "৳60,000.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "home-furniture",
    subcategory: "sofas",
    featured: false,
    bestselling: true,
    latest: true,
    rating: 4.7,
    description:
      "Contemporary L-shaped sofa set that maximizes seating space. Perfect for modern homes and entertainment areas.",
  },
  {
    id: "4",
    name: "P-222 Premium Sectional Sofa",
    price: "৳35,000.00",
    oldPrice: "৳40,000.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "home-furniture",
    subcategory: "sofas",
    featured: true,
    bestselling: false,
    latest: true,
    rating: 4.6,
    description:
      "Premium sectional sofa with modular design. Rearrange to fit your space perfectly.",
  },
  {
    id: "5",
    name: "Office Visitor Chair",
    price: "৳5,000.00",
    oldPrice: "৳6,000.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "office-furniture",
    subcategory: "chairs",
    featured: false,
    bestselling: true,
    latest: false,
    rating: 4.5,
    description:
      "Comfortable visitor chair for your office or reception area. Durable construction with ergonomic design.",
  },
  {
    id: "6",
    name: "Office Visitor Chair with Armrest",
    price: "৳6,500.00",
    oldPrice: "৳7,500.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "office-furniture",
    subcategory: "chairs",
    badge: "Hot",
    featured: true,
    bestselling: true,
    latest: false,
    rating: 4.7,
    description:
      "Enhanced visitor chair with comfortable armrests. Perfect for extended meetings and conferences.",
  },
  {
    id: "7",
    name: "Manager Chair Series",
    price: "৳12,000.00",
    oldPrice: "৳15,000.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "office-furniture",
    subcategory: "chairs",
    featured: true,
    bestselling: false,
    latest: true,
    rating: 4.9,
    description:
      "Premium manager chair with adjustable height and tilt. Provides excellent lumbar support for long working hours.",
  },
  {
    id: "8",
    name: "Executive Manager Chair",
    price: "৳15,000.00",
    oldPrice: "৳18,000.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "office-furniture",
    subcategory: "chairs",
    featured: false,
    bestselling: true,
    latest: true,
    rating: 5.0,
    description:
      "Luxurious executive chair with premium leather upholstery. The ultimate statement piece for your office.",
  },
  {
    id: "9",
    name: "Dining Table Set - 6 Seater",
    price: "৳30,000.00",
    oldPrice: "৳35,000.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "home-furniture",
    subcategory: "dining-room",
    featured: true,
    bestselling: true,
    latest: false,
    rating: 4.8,
    description:
      "Complete dining set with table and 6 chairs. Perfect for family meals and entertaining guests.",
  },
  {
    id: "10",
    name: "King Size Bed Frame",
    price: "৳40,000.00",
    oldPrice: "৳45,000.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "home-furniture",
    subcategory: "bedroom",
    featured: true,
    bestselling: false,
    latest: true,
    rating: 4.9,
    description:
      "Elegant king size bed frame with storage drawers. Combines style with practicality.",
  },
  {
    id: "11",
    name: "Coffee Table with Glass Top",
    price: "৳8,000.00",
    oldPrice: "৳10,000.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "home-furniture",
    subcategory: "living-room",
    featured: false,
    bestselling: true,
    latest: true,
    rating: 4.6,
    description:
      "Modern coffee table with tempered glass top and wooden base. A stylish centerpiece for your living room.",
  },
  {
    id: "12",
    name: "Bookshelf with 5 Shelves",
    price: "৳7,000.00",
    oldPrice: "৳8,500.00",
    image: "/placeholder.svg?height=200&width=200",
    category: "home-furniture",
    subcategory: "living-room",
    featured: true,
    bestselling: false,
    latest: true,
    rating: 4.7,
    description:
      "Spacious bookshelf with 5 adjustable shelves. Perfect for displaying books, photos, and decorative items.",
  },
];
